# Generated by Django 3.1.6 on 2021-02-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='test-product'),
            preserve_default=False,
        ),
    ]
