# Generated by Django 3.1.6 on 2021-02-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeans', '0002_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
